In [38]:
import urllib3
from urllib3 import *
import pandas as pd
from pandas import DataFrame
from pandas import ExcelWriter
import pandas_datareader.data as wb
#import pandas_datareader as pdr
#from pandas_datareader import *
#from pandas_datareader import data, wb
#import pandas.io.data as wb
#from pandas.io.data import Options
#from pandas_datareader import Options
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import scipy
from scipy import stats
from scipy.stats import norm
from scipy.stats import spearmanr
import sys
import datetime
from Quandl import Quandl
import os
import time
import matplotlib.cbook as cbook
import html5lib
import csv
import urllib2
from urllib2 import *
import statsmodels.formula.api as sm
import seaborn as sns
import math as mth
from math import exp
import pylab
#import pymc3 as pm
#from pymc3 import *
import pickle
from bs4 import BeautifulSoup
import re
import html2text
import nltk
from selenium import webdriver
import string
import pprint
import sklearn
from sklearn import svm, preprocessing
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn import cross_validation
from sklearn import grid_search
from sklearn.cross_validation import cross_val_score, ShuffleSplit, cross_val_predict
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.lda import LDA
from sklearn.metrics import confusion_matrix
from sklearn.qda import QDA
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.preprocessing import PolynomialFeatures
import sklearn.preprocessing, sklearn.pipeline

import pandas_ml as pdml
from sklearn_pandas import DataFrameMapper, cross_val_score

sns.set_style("dark")
#sns.set_style("darkgrid")
#sns.set(style="darkgrid", palette="Set2")
#sns.set(style="darkgrid", context="paper", font="monospace")

%matplotlib inline
mpl.style.use('ggplot')

In [58]:
#sd = pd.read_csv("C:\Users\zanderl\Documents\ShortFloatDataCSV.csv",index_col=0, parse_dates=True)
#sd = pd.read_excel("C:\Users\zanderl\Documents\Short Float Research 2_v2.xlsx",sheetname='To CSV Export',index_col=0,parse_dates=True,na_values='NM')
#sd = pd.read_excel("C:\Users\zanderl\Documents\FX_Data_1.xlsx",sheetname='AUDUSD',index_col=0,parse_dates=True,na_values='NM')

start = datetime.datetime(2009,1,1)
end = datetime.datetime.today()


ticker_list = [
'BLK',
'BBBY',
'REGN',
'CMG',
'AMGN',
'ALXN',
'IBB',
'BIIB',
'BIDU',
'FB',
'GS',
'ULTA',
'NFLX',
'TSLA',
'WYNN',
'GOOGL',
'AMZN',
'PCLN',
'AGN',
'AAP',
'ELLI',
'^GSPC',
'AAPL',
'CVX',
'XOM',
'CME',
'C',
'COST',
'DAL',
'GWPH',
'^DJI',
'^VIX',
'JPM',
'V',
'SCTY',
'FSLR',
'FDX',
'FAST',
'HD',
'ILMN']


#ticker_list = ['GOOGL','TSLA','PCLN','AMZN']

def stock_data():
    for ticker in ticker_list:
        stks = wb.DataReader(ticker_list, 'yahoo', start, end)
    return stks

#df = stock_data()

#df = df.fillna(method='pad',axis='minor_axis',inplace=True)
#df = df.fillna(method='bfill',axis='minor_axis',inplace=True)

#sd = df
stock_data()

<class 'pandas.core.panel.Panel'>
Dimensions: 6 (items) x 1891 (major_axis) x 40 (minor_axis)
Items axis: Open to Adj Close
Major_axis axis: 2009-01-02 00:00:00 to 2016-07-07 00:00:00
Minor_axis axis: AAP to ^VIX

In [59]:
df = stock_data()
print(df)

<class 'pandas.core.panel.Panel'>
Dimensions: 6 (items) x 1891 (major_axis) x 40 (minor_axis)
Items axis: Open to Adj Close
Major_axis axis: 2009-01-02 00:00:00 to 2016-07-07 00:00:00
Minor_axis axis: AAP to ^VIX


In [108]:
sd = df['Adj Close']

sd['Weekday'] = sd.index.dayofweek
sd['Day of year'] = sd.index.dayofyear
sd['Days_in_month'] = sd.index.days_in_month
sd['Month'] = sd.index.month
sd['Week of year'] = sd.index.weekofyear
sd['Quarter'] = sd.index.quarter
sd['Year'] = sd.index.year

'''
n=4.0
e_y = (1.0/n)

d_i = 10.0
a_i = 5.0
j_i = 3.0

d_n = 2.0
a_n = 2.0
j_n = 2.0

sd['prod_gm'] = (sd['Open'] * sd['High'] * sd['Low'] * sd['Close Price Adjusted'])
sd['GeoMean'] = sd['prod_gm'].apply(lambda x: mth.pow(x,e_y))

sd['LnR_GeoMean_Delta'] = ((np.log(sd['GeoMean']) - np.log(sd['GeoMean']).shift(d_i)) / d_n)
sd['Exp_Delta'] = sd['LnR_GeoMean_Delta'].apply(lambda x: np.exp(x))

sd['LnR_GeoMean_Accel'] = ((np.log(sd['Exp_Delta']) - np.log(sd['Exp_Delta']).shift(a_i)) / a_n)
sd['Exp_Accel'] = sd['LnR_GeoMean_Accel'].apply(lambda x: np.exp(x))

sd['LnR_GeoMean_Jerk'] = ((np.log(sd['Exp_Accel']) - np.log(sd['Exp_Accel']).shift(j_i)) / j_n)
sd['Exp_Jerk'] = sd['LnR_GeoMean_Jerk'].apply(lambda x: np.exp(x))

sd['OneLine'] = 1.00
'''

sd.head(5)

AAP       AAPL         AGN       ALXN       AMGN  \
Date                                                                 
2013-05-01  83.828116  58.618327  104.389999  96.669998  97.913159   
2013-05-02  84.076599  59.449650  106.489998  96.199997  98.896594   
2013-05-03  84.046782  60.044790  106.459999  98.169998  99.730183   
2013-05-06  84.394664  61.476583  107.199997  97.070000  98.184776   
2013-05-07  85.060596  61.203037  107.220001  96.349998  97.838228   

                  AMZN       BBBY       BIDU        BIIB         BLK   ...    \
Date                                                                   ...     
2013-05-01  248.229996  68.609082  84.860001  214.330002  240.794253   ...     
2013-05-02  252.550003  69.516429  85.000000  217.300003  242.095398   ...     
2013-05-03  258.049988  68.369785  84.510002  218.850006  250.391321   ...     
2013-05-06  255.720001  69.446634  87.650002  215.729996  253.168944   ...     
2013-05-07  257.730011  69.865406  89.300003  212.550003  254.276282   ...     

             ^VIX  Weekday  Day of year  Days_in_month  Month  Week of year  \
Date                                                                          
2013-05-01  14.49        2          121             31      5            18   
2013-05-02  13.59        3          122             31      5            18   
2013-05-03  12.85        4          123             31      5            18   
2013-05-06  12.66        0          126             31      5            19   
2013-05-07  12.83        1          127             31      5            19   

            Quarter  Year     y_future  labels  
Date                                            
2013-05-01        2  2013  1617.500000       1  
2013-05-02        2  2013  1625.959961       1  
2013-05-03        2  2013  1632.689941       1  
2013-05-06        2  2013  1626.670044       1  
2013-05-07        2  2013  1633.699951       1  

[5 rows x 49 columns]

In [109]:
#sd.drop(['Bid Price','Offer Price','Quarter','Year','Days_in_month','Close Price Adjusted'],axis=1,inplace=True)
#sd.drop(['Month','Weekday','Last Sale Price','Market Cap',
#         'Year','Quarter','Days_in_month','Week of year','Short Float (%)',
#        'Bid Price','Offer Price','Low','High','Open'],axis=1,inplace=True)
pd.isnull(sd).sum()

AAP              0
AAPL             0
AGN              0
ALXN             0
AMGN             0
AMZN             0
BBBY             0
BIDU             0
BIIB             0
BLK              0
C                0
CME              0
CMG              0
COST             0
CVX              0
DAL              0
ELLI             0
FAST             0
FB               0
FDX              0
FSLR             0
GOOGL            0
GS               0
GWPH             0
HD               0
IBB              0
ILMN             0
JPM              0
NFLX             0
PCLN             0
REGN             0
SCTY             0
TSLA             0
ULTA             0
V                0
WYNN             0
XOM              0
^DJI             0
^GSPC            0
^VIX             0
Weekday          0
Day of year      0
Days_in_month    0
Month            0
Week of year     0
Quarter          0
Year             0
y_future         0
labels           0
dtype: int64

In [110]:
sd.fillna(method='pad',axis=0,inplace=True)
#sd.replace({'NM':'NaN'})
sd.dropna(axis=0,inplace=True)

In [111]:
pd.isnull(sd).sum()

AAP              0
AAPL             0
AGN              0
ALXN             0
AMGN             0
AMZN             0
BBBY             0
BIDU             0
BIIB             0
BLK              0
C                0
CME              0
CMG              0
COST             0
CVX              0
DAL              0
ELLI             0
FAST             0
FB               0
FDX              0
FSLR             0
GOOGL            0
GS               0
GWPH             0
HD               0
IBB              0
ILMN             0
JPM              0
NFLX             0
PCLN             0
REGN             0
SCTY             0
TSLA             0
ULTA             0
V                0
WYNN             0
XOM              0
^DJI             0
^GSPC            0
^VIX             0
Weekday          0
Day of year      0
Days_in_month    0
Month            0
Week of year     0
Quarter          0
Year             0
y_future         0
labels           0
dtype: int64

In [112]:
#sd['Short Float (%)'].plot(figsize=(12,8))

In [113]:
df1 = sd

In [114]:
def dvar(d_curr,d_fut):
    if d_fut > d_curr:
        return 1
    if d_fut < d_curr:
        return -1
    else:
        return 0

In [115]:
#df1 = df1.apply(lambda x: np.log(x))
df1.head(1)

AAP       AAPL         AGN       ALXN       AMGN  \
Date                                                                 
2013-05-01  83.828116  58.618327  104.389999  96.669998  97.913159   

                  AMZN       BBBY       BIDU        BIIB         BLK   ...    \
Date                                                                   ...     
2013-05-01  248.229996  68.609082  84.860001  214.330002  240.794253   ...     

             ^VIX  Weekday  Day of year  Days_in_month  Month  Week of year  \
Date                                                                          
2013-05-01  14.49        2          121             31      5            18   

            Quarter  Year  y_future  labels  
Date                                         
2013-05-01        2  2013    1617.5       1  

[1 rows x 49 columns]

In [116]:
#df1.columns
feature_names = list(df1.columns.values)
feature_names

['AAP',
 'AAPL',
 'AGN',
 'ALXN',
 'AMGN',
 'AMZN',
 'BBBY',
 'BIDU',
 'BIIB',
 'BLK',
 'C',
 'CME',
 'CMG',
 'COST',
 'CVX',
 'DAL',
 'ELLI',
 'FAST',
 'FB',
 'FDX',
 'FSLR',
 'GOOGL',
 'GS',
 'GWPH',
 'HD',
 'IBB',
 'ILMN',
 'JPM',
 'NFLX',
 'PCLN',
 'REGN',
 'SCTY',
 'TSLA',
 'ULTA',
 'V',
 'WYNN',
 'XOM',
 '^DJI',
 '^GSPC',
 '^VIX',
 'Weekday',
 'Day of year',
 'Days_in_month',
 'Month',
 'Week of year',
 'Quarter',
 'Year',
 'y_future',
 'labels']

In [117]:
df1.shape

(800, 49)

In [118]:
df1.dropna(inplace=True)

In [119]:
df1.shape

(800, 49)

In [120]:
st='^GSPC'
df1['y_future'] = df1[st].shift(-3)

In [121]:
df1['labels'] = list(map(dvar,df1[st],df1['y_future']))

In [122]:
X = pd.DataFrame(df1, index=df1.index)
y = pd.DataFrame(df1, index=df1.index)

X = X.drop(['y_future', 'labels'],axis=1)
y = df1['labels']

In [123]:
#pd.isnull(df1).sum()

In [124]:
df1.dropna(inplace=True)
#X.replace({'NM':'NaN'})
pd.isnull(X).sum()

AAP              0
AAPL             0
AGN              0
ALXN             0
AMGN             0
AMZN             0
BBBY             0
BIDU             0
BIIB             0
BLK              0
C                0
CME              0
CMG              0
COST             0
CVX              0
DAL              0
ELLI             0
FAST             0
FB               0
FDX              0
FSLR             0
GOOGL            0
GS               0
GWPH             0
HD               0
IBB              0
ILMN             0
JPM              0
NFLX             0
PCLN             0
REGN             0
SCTY             0
TSLA             0
ULTA             0
V                0
WYNN             0
XOM              0
^DJI             0
^GSPC            0
^VIX             0
Weekday          0
Day of year      0
Days_in_month    0
Month            0
Week of year     0
Quarter          0
Year             0
dtype: int64

In [125]:
X = preprocessing.scale(X)

In [188]:
n_samples, n_features = X.shape
print("n_samples=%d" % n_samples)
print("n_features=%d" % n_features)

X_train, X_test, y_train, y_test = cross_validation.train_test_split(X,y, test_size=0.50)
cv = ShuffleSplit(n_samples,n_iter=10,test_size=.50,random_state=None)

n_samples=800
n_features=47


In [189]:
type(X_test)

numpy.ndarray

In [190]:
len(df1['labels'])

797

In [133]:
models = [("LR", LogisticRegression()),
         ("LDA", LDA()),
         ("QDA", QDA()),
         ("LSVC", LinearSVC()),
         ("RSVM", SVC(C=1000000.0, cache_size=200, kernel='rbf',gamma=0.0001,
                      probability=True,random_state=None,shrinking=True,
                      tol=0.001,verbose=False)
          ),
         ("RF", RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=None,min_samples_split=2,
                                       min_samples_leaf=1,max_features='auto',bootstrap=False,oob_score=False,
                                       n_jobs=-1,random_state=None,verbose=0)
         ),
         ("KNN", KNeighborsClassifier()LD
          ),
          ("ETC", ExtraTreesClassifier(n_estimators=100, criterion='gini', max_depth=None, 
                                      min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
                                      max_features='auto', max_leaf_nodes=None, bootstrap=False, 
                                      oob_score=False, n_jobs=-1, random_state=None, verbose=0, 
                                      warm_start=False, class_weight=None))]

Below we'll iterate through the models with a loop that trains them

In [134]:
for m in models:
    #Train the models on the training data
    m[1].fit(X_train, y_train)
    
    #Make an array of predictions on the testing data in the test set
    pred = m[1].predict(X_test)
    
    print("%s:\n%0.3f" % (m[0], m[1].score(X_test, y_test)))
    print("%s\n" % confusion_matrix(pred,y_test))

LR:
0.675
[[ 78   0  44]
 [  0   0   0]
 [ 83   3 192]]

LDA:
0.665
[[ 85   1  55]
 [  0   0   0]
 [ 76   2 181]]

QDA:
0.675
[[ 76   0  42]
 [  0   0   0]
 [ 85   3 194]]

LSVC:
0.680
[[ 86   0  50]
 [  0   0   0]
 [ 75   3 186]]

RSVM:
0.715
[[103   0  53]
 [  0   0   0]
 [ 58   3 183]]

RF:
0.748
[[109   2  46]
 [  0   0   0]
 [ 52   1 190]]

KNN:
0.637
[[ 86   0  67]
 [  0   0   0]
 [ 75   3 169]]

ETC:
0.743
[[102   0  41]
 [  0   0   0]
 [ 59   3 195]]



In [135]:
type(models)

list

In [136]:
RF2 = RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=None,min_samples_split=2,
                                       min_samples_leaf=1,max_features='auto',bootstrap=False,oob_score=False,
                                       n_jobs=-1,random_state=None,verbose=0)

ETC2 = ExtraTreesClassifier(n_estimators=100, criterion='gini', max_depth=None, 
                                      min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
                                      max_features='auto', max_leaf_nodes=None, bootstrap=False, 
                                      oob_score=False, n_jobs=-1, random_state=None, verbose=0, 
                                      warm_start=False, class_weight=None)

In [137]:
RF2.fit(X_train, y_train)
ETC2.fit(X_train, y_train)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [138]:
#print "Features sorted by their score:"
#print sorted(zip(map(lambda x: round(x, 4), RF2.feature_importances_), feature_names),
#             reverse=True)

In [176]:
feat_importance = sorted(zip(map(lambda x: round(x, 4), RF2.feature_importances_), feature_names),
             reverse=True)
print "Features sorted by their score:"
feat_importance

Features sorted by their score:


[(0.0399, 'FAST'),
 (0.0374, '^VIX'),
 (0.0363, 'JPM'),
 (0.0328, 'WYNN'),
 (0.0307, 'C'),
 (0.0282, 'GOOGL'),
 (0.0281, 'SCTY'),
 (0.0275, 'ULTA'),
 (0.0268, 'GS'),
 (0.0265, 'PCLN'),
 (0.0263, 'CMG'),
 (0.0258, '^DJI'),
 (0.0252, 'AGN'),
 (0.0251, 'BLK'),
 (0.0236, 'DAL'),
 (0.0231, 'NFLX'),
 (0.0231, 'FDX'),
 (0.0229, '^GSPC'),
 (0.0229, 'BIIB'),
 (0.0225, 'V'),
 (0.0222, 'AAPL'),
 (0.0221, 'Day of year'),
 (0.0219, 'XOM'),
 (0.0218, 'REGN'),
 (0.0216, 'TSLA'),
 (0.0211, 'CVX'),
 (0.0208, 'FSLR'),
 (0.0208, 'CME'),
 (0.0203, 'Week of year'),
 (0.0203, 'AAP'),
 (0.0194, 'AMGN'),
 (0.0193, 'ELLI'),
 (0.0192, 'ILMN'),
 (0.019, 'BIDU'),
 (0.0187, 'FB'),
 (0.0186, 'HD'),
 (0.0184, 'BBBY'),
 (0.0182, 'GWPH'),
 (0.0178, 'COST'),
 (0.0172, 'ALXN'),
 (0.0166, 'AMZN'),
 (0.0136, 'IBB'),
 (0.0056, 'Weekday'),
 (0.0054, 'Month'),
 (0.0033, 'Days_in_month'),
 (0.0016, 'Quarter'),
 (0.0007, 'Year')]

In [177]:
feat_importance_ETC2 = sorted(zip(map(lambda x: round(x, 4), ETC2.feature_importances_), feature_names),
             reverse=True)
print "Features sorted by their score:"
feat_importance_ETC2

Features sorted by their score:


[(0.0586, 'FAST'),
 (0.041, 'GS'),
 (0.0338, '^GSPC'),
 (0.0317, 'GOOGL'),
 (0.0312, 'AMGN'),
 (0.0311, 'C'),
 (0.0279, 'BLK'),
 (0.0258, 'AGN'),
 (0.0253, 'CMG'),
 (0.0249, '^DJI'),
 (0.0244, 'Day of year'),
 (0.0243, '^VIX'),
 (0.024, 'ULTA'),
 (0.0235, 'TSLA'),
 (0.0234, 'FSLR'),
 (0.0231, 'CVX'),
 (0.0228, 'REGN'),
 (0.0226, 'ELLI'),
 (0.0218, 'XOM'),
 (0.021, 'AAP'),
 (0.0209, 'Week of year'),
 (0.0205, 'BBBY'),
 (0.0204, 'AAPL'),
 (0.0199, 'GWPH'),
 (0.0198, 'AMZN'),
 (0.0197, 'SCTY'),
 (0.0197, 'HD'),
 (0.0196, 'V'),
 (0.0196, 'PCLN'),
 (0.0196, 'FDX'),
 (0.019, 'ILMN'),
 (0.019, 'COST'),
 (0.019, 'ALXN'),
 (0.0181, 'IBB'),
 (0.018, 'JPM'),
 (0.018, 'BIIB'),
 (0.0178, 'CME'),
 (0.0174, 'NFLX'),
 (0.0174, 'BIDU'),
 (0.0173, 'WYNN'),
 (0.0162, 'DAL'),
 (0.0154, 'FB'),
 (0.0106, 'Days_in_month'),
 (0.0061, 'Weekday'),
 (0.006, 'Month'),
 (0.0019, 'Quarter'),
 (0.0004, 'Year')]

In [178]:
'''
for cv_index, (train, test) in enumerate(cv):
    print("# Cross Validation Iteration #%d" % cv_index)
    print("train indices: {0}...".format(train[:10]))
    print("test indices: {0}...".format(test[:10]))
    
    RF2 = RandomForestClassifier(n_estimators=50,criterion='gini',max_depth=None,min_samples_split=2,
                                       min_samples_leaf=1,max_features='auto',bootstrap=False,oob_score=False,
                                       n_jobs=-1,random_state=None,verbose=0).fit(X[train],y[train])
    print("train score: {0:.3f}, test score: {1:.3f}\n".format(RF2.score(X[train], y[train]), 
          RF2.score(X[test], y[test])))

test_scores_2 = cross_val_score(RF2, X, y, cv=cv, n_jobs=-1)
'''

'\nfor cv_index, (train, test) in enumerate(cv):\n    print("# Cross Validation Iteration #%d" % cv_index)\n    print("train indices: {0}...".format(train[:10]))\n    print("test indices: {0}...".format(test[:10]))\n    \n    RF2 = RandomForestClassifier(n_estimators=50,criterion=\'gini\',max_depth=None,min_samples_split=2,\n                                       min_samples_leaf=1,max_features=\'auto\',bootstrap=False,oob_score=False,\n                                       n_jobs=-1,random_state=None,verbose=0).fit(X[train],y[train])\n    print("train score: {0:.3f}, test score: {1:.3f}\n".format(RF2.score(X[train], y[train]), \n          RF2.score(X[test], y[test])))\n\ntest_scores_2 = cross_val_score(RF2, X, y, cv=cv, n_jobs=-1)\n'

In [179]:
'''
from scipy.stats import sem

def mean_score(scores):
    """Print the empirical mean score and standard error of the mean."""
    return ("Mean score: {0:.3f} (+/-{1:.3f})").format(np.mean(scores), sem(scores))

print (test_scores_2)
print (mean_score(test_scores_2))
'''

'\nfrom scipy.stats import sem\n\ndef mean_score(scores):\n    """Print the empirical mean score and standard error of the mean."""\n    return ("Mean score: {0:.3f} (+/-{1:.3f})").format(np.mean(scores), sem(scores))\n\nprint (test_scores_2)\nprint (mean_score(test_scores_2))\n'

In [180]:
'''
for cv_index, (train, test) in enumerate(cv):
    print("# Cross Validation Iteration #%d" % cv_index)
    print("train indices: {0}...".format(train[:10]))
    print("test indices: {0}...".format(test[:10]))
    
    ETC2 = RandomForestClassifier(n_estimators=50,criterion='gini',max_depth=None,min_samples_split=2,
                                       min_samples_leaf=1,max_features='auto',bootstrap=False,oob_score=False,
                                       n_jobs=-1,random_state=None,verbose=0).fit(X[train],y[train])
    print("train score: {0:.3f}, test score: {1:.3f}\n".format(ETC2.score(X[train], y[train]), 
          ETC2.score(X[test], y[test])))

test_scores_3 = cross_val_score(ETC2, X, y, cv=cv, n_jobs=-1)
'''

'\nfor cv_index, (train, test) in enumerate(cv):\n    print("# Cross Validation Iteration #%d" % cv_index)\n    print("train indices: {0}...".format(train[:10]))\n    print("test indices: {0}...".format(test[:10]))\n    \n    ETC2 = RandomForestClassifier(n_estimators=50,criterion=\'gini\',max_depth=None,min_samples_split=2,\n                                       min_samples_leaf=1,max_features=\'auto\',bootstrap=False,oob_score=False,\n                                       n_jobs=-1,random_state=None,verbose=0).fit(X[train],y[train])\n    print("train score: {0:.3f}, test score: {1:.3f}\n".format(ETC2.score(X[train], y[train]), \n          ETC2.score(X[test], y[test])))\n\ntest_scores_3 = cross_val_score(ETC2, X, y, cv=cv, n_jobs=-1)\n'

In [181]:
'''
from scipy.stats import sem

def mean_score(scores):
    """Print the empirical mean score and standard error of the mean."""
    return ("Mean score: {0:.3f} (+/-{1:.3f})").format(np.mean(scores), sem(scores))

print (test_scores_3)
print (mean_score(test_scores_3))
'''

'\nfrom scipy.stats import sem\n\ndef mean_score(scores):\n    """Print the empirical mean score and standard error of the mean."""\n    return ("Mean score: {0:.3f} (+/-{1:.3f})").format(np.mean(scores), sem(scores))\n\nprint (test_scores_3)\nprint (mean_score(test_scores_3))\n'

test_scores_3 = cross_val_score(knn, X, y, cv=cv, n_jobs=1)

for cv_index, (train, test) in enumerate(cv):
    print("# Cross Validation Iteration #%d" % cv_index)
    print("train indices: {0}...".format(train[:10]))
    print("test indices: {0}...".format(test[:10]))
    
    knn = KNeighborsClassifier(n_neighbors=5,algorithm='auto').fit(X[train],y[train])
    print("train score: {0:.3f}, test score: {1:.3f}\n".format(knn.score(X[train], y[train]), 
          knn.score(X[test], y[test])))

def mean_score(scores):
    """Print the empirical mean score and standard error of the mean."""
    return ("Mean score: {0:.3f} (+/-{1:.3f})").format(np.mean(scores), sem(scores))

print (test_scores_3)
print (mean_score(test_scores_3))

In [182]:
#predicted_values_RF2 = cross_val_predict(RF2,X_test,y_test,cv=10,n_jobs=-1,
#                                        verbose=0,fit_params=None,pre_dispatch='2*n_jobs')

In [183]:
#predicted_values_RF2

In [184]:
'''
for cv_index, (train, test) in enumerate(cv):
    print("# Cross Validation Iteration #%d" % cv_index)
    print("train indices: {0}...".format(train[:10]))
    print("test indices: {0}...".format(test[:10]))
    
    ETC2 = RandomForestClassifier(n_estimators=50,criterion='gini',max_depth=None,min_samples_split=2,
                                       min_samples_leaf=1,max_features='auto',bootstrap=False,oob_score=False,
                                       n_jobs=-1,random_state=None,verbose=0).fit(X[train],y[train])
    print("train score: {0:.3f}, test score: {1:.3f}\n".format(ETC2.score(X[train], y[train]), 
          ETC2.score(X[test], y[test])))

predicted_values_ETC2 = cross_val_predict(ETC2, X, y, cv=10, n_jobs=-1)
'''

'\nfor cv_index, (train, test) in enumerate(cv):\n    print("# Cross Validation Iteration #%d" % cv_index)\n    print("train indices: {0}...".format(train[:10]))\n    print("test indices: {0}...".format(test[:10]))\n    \n    ETC2 = RandomForestClassifier(n_estimators=50,criterion=\'gini\',max_depth=None,min_samples_split=2,\n                                       min_samples_leaf=1,max_features=\'auto\',bootstrap=False,oob_score=False,\n                                       n_jobs=-1,random_state=None,verbose=0).fit(X[train],y[train])\n    print("train score: {0:.3f}, test score: {1:.3f}\n".format(ETC2.score(X[train], y[train]), \n          ETC2.score(X[test], y[test])))\n\npredicted_values_ETC2 = cross_val_predict(ETC2, X, y, cv=10, n_jobs=-1)\n'

In [185]:
#predicted_values_ETC2

In [186]:
#len(predicted_values_ETC2)

In [187]:
#RF2_predict_values

lenval = len(svr_predicted_values) * -1
y_actual = y[lenval:]
results_df = pd.DataFrame(y_actual, index=y_actual.index)
results_df['y_pred'] = svr_predicted_values


def  prediction_labels(pred_data):
    if pred_data > 0:
        return 1
    if pred_data < 0:
        return -1
    else:
        return 0


#results_df['y_pred_labels'] = list(map(prediction_labels,results_df['y_pred']))

svc_predict_values = clf.predict(X_test)
lenval_svc = len(svc_predict_values) * -1
y_actual_svc = y[lenval_svc:]
results_clf_df = pd.DataFrame(y_actual_svc,index=y_actual_svc.index)
results_clf_df['y_pred_svc'] = svc_predict_values

cm_r = confusion_matrix(results_df['labels'],results_df['y_pred_labels'])
cm_r

results_clf_df.head(5)

cm_svc = confusion_matrix(results_clf_df['labels'],results_clf_df['y_pred_svc'])
cm_svc

results_df['y_pred'].apply(lambda x: np.exp(x))
results_df['y_pred'].head(5)

svr_predicted_values

In [198]:
def RF2_Test_Shuffle_Confidence():
    
    st='^GSPC'
    df1['y_future'] = df1[st].shift(-3)

    df1['labels'] = list(map(dvar,df1[st],df1['y_future']))

    X = pd.DataFrame(df1, index=df1.index)
    y = pd.DataFrame(df1, index=df1.index)

    X = X.drop(['y_future', 'labels'],axis=1)
    y = df1['labels']
    
    for i in y:
        np.random.shuffle(y)
    
    df1.dropna(inplace=True)

    X = preprocessing.scale(X)
    X_train, X_test, y_train, y_test = cross_validation.train_test_split(X,y, test_size=0.50)
    
    
    RF2 = RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=None,min_samples_split=2,
                                       min_samples_leaf=1,max_features='auto',bootstrap=False,oob_score=False,
                                       n_jobs=-1,random_state=None,verbose=0)
    
    RF2.fit(X_train, y_train)
    
    pred1 = RF2.predict(X_test)
    confidence = RF2.score(X_test, y_test)
    return pred1, confidence
    

In [ ]:
for _ in range(10):
    R2TS = RF2_Test_Shuffle_Confidence()