In [4]:
import pandas as pd
import time
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import sys
import datetime
import os
import seaborn as sns
import math as mth
import pickle
import re
import nltk
import spacy
import sklearn

import tika
from tika import parser

import bokeh
from bokeh.plotting import *
from bokeh.io import output_notebook
from bokeh.models import Toggle, BoxAnnotation, CustomJS, HoverTool

output_notebook()

from sklearn.manifold import TSNE

#import plotly
#from plotly.graph_objs import *
#import plotly.plotly as py
#import plotly.tools as tls
#from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

#import plotly.offline as offline
#offline.init_notebook_mode(connected=False)
#init_notebook_mode(connected=False)

#import cufflinks as cf
#import colorlover as cl

#Plotly API Information:(username='asl4af', api_key='7ut55tktdt')
#plotly.tools.set_credentials_file(username='Zanderl',api_key='2NRGAPpIAjvFhmUZ8dQF')

#Make all charts public and set a global theme
#cf.set_config_file(world_readable=True,theme='white',offline=True)

#tls.embed('https://plot.ly/~cufflinks/8')

sns.set_style("white")

%matplotlib inline

from IPython.display import display

from IPython.display import HTML

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

Loading BokehJS ...

In [5]:
import sklearn
from sklearn import svm, preprocessing
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn import cross_validation
from sklearn import grid_search
from sklearn.cross_validation import cross_val_score, ShuffleSplit, cross_val_predict
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.preprocessing import PolynomialFeatures
import sklearn.preprocessing, sklearn.pipeline

C:\Users\zanderl\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\zanderl\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [6]:
df1 = pd.read_csv('C:/Users/zanderl/Documents/Individual and IP data 3.csv',encoding='latin1')

In [7]:
df1.head()

Sum of Emails per Opp  Sum of Age  Sum of Amount Increase  \
0                      0           7                       1   
1                      0         127                       1   
2                      3         119                       2   
3                      4           4                       0   
4                      1          98                       1   

   Sum of Amount Decrease  Sum of # of Stage Changes  Sum of 2 - Concern  \
0                       0                          2                   0   
1                       0                          3                  18   
2                       1                          3                 170   
3                       0                          2                   0   
4                       0                          2                   0   

   Sum of New Client (# assignment)  Sum of 2 - Aware  Sum of Created Month  \
0                                 0                 7                     9   
1                                 0                 0                     9   
2                                 1                 0                    10   
3                                 0                 4                    10   
4                                 0                 0                    10   

   Sum of 02_Data Management Solutions  Sum of Closed Won Opps per Opp Owner  \
0                                    1                                    30   
1                                    0                                    18   
2                                    0                                    31   
3                                    1                                    34   
4                                    0                                    34   

   Sum of Closed Lost Opps per Opp Owner  Sum of Won  
0                                     71           0  
1                                     86           0  
2                                     93           0  
3                                     83           0  
4                                     83           0

In [8]:
df1.describe()

Sum of Emails per Opp   Sum of Age  Sum of Amount Increase  \
count             225.000000   225.000000              225.000000   
mean                1.168889   169.951111                0.595556   
std                 3.617654   365.513169                0.959435   
min                 0.000000     0.000000                0.000000   
25%                 0.000000     0.000000                0.000000   
50%                 0.000000    32.000000                0.000000   
75%                 0.000000   177.000000                1.000000   
max                23.000000  2922.000000                7.000000   

       Sum of Amount Decrease  Sum of # of Stage Changes  Sum of 2 - Concern  \
count              225.000000                  225.00000          225.000000   
mean                 0.306667                    2.88000            8.724444   
std                  0.778735                    2.39583           37.723673   
min                  0.000000                    0.00000            0.000000   
25%                  0.000000                    2.00000            0.000000   
50%                  0.000000                    2.00000            0.000000   
75%                  0.000000                    3.00000            0.000000   
max                  7.000000                   17.00000          352.000000   

       Sum of New Client (# assignment)  Sum of 2 - Aware  \
count                        225.000000        225.000000   
mean                           0.244444         24.791111   
std                            0.430716        103.768741   
min                            0.000000          0.000000   
25%                            0.000000          0.000000   
50%                            0.000000          0.000000   
75%                            0.000000          0.000000   
max                            1.000000        981.000000   

       Sum of Created Month  Sum of 02_Data Management Solutions  \
count            225.000000                           225.000000   
mean               6.173333                             0.551111   
std                3.351599                             0.498490   
min                1.000000                             0.000000   
25%                3.000000                             0.000000   
50%                6.000000                             1.000000   
75%                9.000000                             1.000000   
max               12.000000                             1.000000   

       Sum of Closed Won Opps per Opp Owner  \
count                            225.000000   
mean                              27.706667   
std                               11.369728   
min                                0.000000   
25%                               26.000000   
50%                               31.000000   
75%                               34.000000   
max                               74.000000   

       Sum of Closed Lost Opps per Opp Owner  Sum of Won  
count                             225.000000  225.000000  
mean                               39.275556    0.546667  
std                                39.734213    0.498927  
min                                 0.000000    0.000000  
25%                                 3.000000    0.000000  
50%                                25.000000    1.000000  
75%                                83.000000    1.000000  
max                               172.000000    1.000000

In [9]:
#pd.isnull(df1).sum()

In [10]:
X = pd.DataFrame(df1, index=df1.index)
y = pd.Series(df1['Sum of Won'], index=df1.index)

#X = df1.drop(labels=('Sum of Won'),axis=1,inplace=True)
#y = df1['Sum of Won']

In [11]:
X.drop(labels=('Sum of Won'),axis=1,inplace=True)

In [12]:
X.head()

Sum of Emails per Opp  Sum of Age  Sum of Amount Increase  \
0                      0           7                       1   
1                      0         127                       1   
2                      3         119                       2   
3                      4           4                       0   
4                      1          98                       1   

   Sum of Amount Decrease  Sum of # of Stage Changes  Sum of 2 - Concern  \
0                       0                          2                   0   
1                       0                          3                  18   
2                       1                          3                 170   
3                       0                          2                   0   
4                       0                          2                   0   

   Sum of New Client (# assignment)  Sum of 2 - Aware  Sum of Created Month  \
0                                 0                 7                     9   
1                                 0                 0                     9   
2                                 1                 0                    10   
3                                 0                 4                    10   
4                                 0                 0                    10   

   Sum of 02_Data Management Solutions  Sum of Closed Won Opps per Opp Owner  \
0                                    1                                    30   
1                                    0                                    18   
2                                    0                                    31   
3                                    1                                    34   
4                                    0                                    34   

   Sum of Closed Lost Opps per Opp Owner  
0                                     71  
1                                     86  
2                                     93  
3                                     83  
4                                     83

In [13]:
#y

In [14]:
#X.dropna(axis=0,inplace=True)

In [15]:
#pd.isnull(X).sum()

In [16]:
from sklearn import preprocessing
X = preprocessing.scale(X)

In [17]:
n_samples, n_features = X.shape
print("n_samples=%d" % n_samples)
print("n_features=%d" % n_features)

X_train, X_test, y_train, y_test = cross_validation.train_test_split(X,y, test_size=0.50)
cv = ShuffleSplit(n_samples,n_iter=10,test_size=.50,random_state=None)

n_samples=225
n_features=12


In [18]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA

In [19]:
models = [("LR", LogisticRegression()),
         ("LDA", LDA()),
         ("QDA", QDA()),
         ("LSVC", LinearSVC()),
         ("RSVM", SVC(C=1000000.0, cache_size=200, kernel='rbf',gamma=0.0001,
                      probability=True,random_state=None,shrinking=True,
                      tol=0.001,verbose=False)
          ),
         ("RF", RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=None,min_samples_split=2,
                                       min_samples_leaf=1,max_features='auto',bootstrap=False,oob_score=False,
                                       n_jobs=-1,random_state=None,verbose=0)
         ),
         ("KNN", KNeighborsClassifier()
          ),
          ("ETC", ExtraTreesClassifier(n_estimators=100, criterion='gini', max_depth=None, 
                                      min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
                                      max_features='auto', max_leaf_nodes=None, bootstrap=False, 
                                      oob_score=False, n_jobs=-1, random_state=None, verbose=0, 
                                      warm_start=False, class_weight=None))]

In [20]:
#X_train.shape
#y_train.shape
y_train.head()

193    1
206    1
51     0
13     0
185    1
Name: Sum of Won, dtype: int64

In [21]:
for m in models:
    #Train the models on the training data
    m[1].fit(X_train, y_train)
    
    #Make an array of predictions on the testing data in the test set
    pred = m[1].predict(X_test)
    
    print("%s:\n%0.3f" % (m[0], m[1].score(X_test, y_test)))
    print("%s\n" % confusion_matrix(pred,y_test))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

LR:
0.912
[[43  4]
 [ 6 60]]



LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)

LDA:
0.903
[[42  4]
 [ 7 60]]



QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
               store_covariance=False, store_covariances=None, tol=0.0001)

QDA:
0.912
[[41  2]
 [ 8 62]]



LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

LSVC:
0.929
[[44  3]
 [ 5 61]]



SVC(C=1000000.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

RSVM:
0.885
[[40  4]
 [ 9 60]]



RandomForestClassifier(bootstrap=False, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

RF:
0.947
[[44  1]
 [ 5 63]]



KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

KNN:
0.894
[[41  4]
 [ 8 60]]



ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

ETC:
0.938
[[45  3]
 [ 4 61]]



In [22]:
import lime

In [29]:
len(models)

8

In [39]:
models[5][1].feature_importances_

array([ 0.04082734,  0.36653777,  0.0278113 ,  0.01538394,  0.14128684,
        0.0150592 ,  0.0313143 ,  0.08673361,  0.02480215,  0.0599996 ,
        0.03004056,  0.1602034 ])